search_rules:
    from-date: 2020-12-24
    to-date: 2020-12-26
    pt-rule: kanye has:geo

search_params:
    results-per-call: 500
    max-results: 500

output_params:
    save_file: True
    filename_prefix: kanye
    results_per_file: 10000000
